# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HtLocalChatClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'CocoaAsyncSocket'
  pod 'WebRTC'
  pod 'MBProgressHUD'
  # Pods for HtLocalChatClient

  target 'HtLocalChatClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HtLocalChatClientUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
