# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HtLocalChatServer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'CocoaAsyncSocket'
  pod 'MBProgressHUD'
  # Pods for HtLocalChatServer

  target 'HtLocalChatServerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HtLocalChatServerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
